#
# Publish to Wiki
#
name: Publish to Wiki

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]
  push:

jobs:
    sync_wiki:
      name: Sync Wiki
      runs-on: ubuntu-latest
      steps:
        - name: Checkout current version
          uses: actions/checkout@v2
        - name: Rename README
          run: mv README.md Home.md
        - name: Sync with Wiki
          uses: kai-tub/external-repo-sync-action@v1
          with:
            source-directory: "."
            commit-message: Syncing Wiki with repo
            exclude-patterns: "LICENSE .github *.yml *.php"
          env:
            GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}    
